services:
  receiver_svc:
    build:
      context: ./receiver
      additional_contexts:
        shared: ./_common
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy

  storage_svc:
    build:
      context: ./storage
      additional_contexts:
        shared: ./_common
    expose:
      - "8090"
    depends_on:
      storage_db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  processor_svc:
    build:
      context: ./processor
      additional_contexts:
        shared: ./_common
    ports:
      - "8100:8100"
    depends_on:
      - storage_svc

  analyzer_svc:
    build:
      context: ./analyzer
      additional_contexts:
        shared: ./_common
    ports:
      - "8110:8110"
    depends_on:
      kafka:
        condition: service_healthy

  storage_db:
    image: mysql:9.6
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: storage_service
      MYSQL_PASSWORD: $$torage_5ervice
      MYSQL_DATABASE: readings
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:4.2.0
    expose:
      - "9092"
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: