version: 1
api:
  file: openapi.yml
  spec_dir: "./"
  strict_validation: true
  validate_responses: true
  cors:
    allow_origins: []
    allow_methods: []
    allow_headers: []
  base_path: "/analyzer"
services:
  self:
    host: 0.0.0.0
    port: 8110
  broker:
    host: kafka
    port: 9092
    topic: events