server {
    listen       80;
    listen  [::]:80;
    server_name  "";

    # Ima set a short TTL using docker's permanent DNS resolver
    # This SHOULD let nginx discover new container IPs if scaled
    resolver 127.0.0.11 valid=5s;

    # dashboard
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # receiver
    location /receiver {
        # apparently this is the best way to force nginx to be open to dynamic IP addresses
        # (other than paying for nginx plus, which is a thing???)
        set $receiver_upstream http://receiver_svc:8080;
        proxy_pass $receiver_upstream;
    }

    # processor
    location /processor {
        proxy_pass http://processor_svc:8100;
    }

    # analyzer
    location /analyzer {
        proxy_pass http://analyzer_svc:8110;
    }

    # health checker
    location /healthcheck {
        proxy_pass http://healthcheck_svc:8120;
    }

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
