version: 1
api:
  file: openapi.yml
  spec_dir: "./"
  strict_validation: true
  validate_responses: true
services:
  self:
    host: 0.0.0.0
    port: 8110
  broker:
    host: kafka
    port: 9092
    topic: events