version: 1
api:
  file: openapi.yml
  spec_dir: "./"
  strict_validation: true
  validate_responses: true
  cors:
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
services:
  self:
    host: 0.0.0.0
    port: 8100
    proc_interval_secs: 60
    stats_file: "/data/stats.json"
    fallback_start_time: "1970-01-01T00:00:00Z"
  storage:
    baseurl: http://storage_svc:8090
    endpoints:
      energy: /plug-data/energy-consumed
      temp: /plug-data/internal-temp